FROM python
WORKDIR /home/devops/devops_docker/

RUN apt-get update && apt-get install -y curl
RUN apt install -y python3-pip python3-dev build-essential libssl-dev libffi-dev python3-setuptools
RUN pip install --no-cache-dir flask

EXPOSE 5000

RUN git clone https://github.com/Anjalo18/DevOps.git

CMD ["python", "DevOps/mydevopspro.py"]
